name: Python leet-test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: Python/problems
       
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with unittest
      run: |
        for dir in Python/problems/*; do
          if [ -d "$dir" ]; then
            cd "$dir"
            if [ -f "test_solution.py" ]; then
              python -m unittest discover -v
            fi
            cd ../..
          fi
        done
